name: update-directory

on:
  schedule:
    # Run every 1st of the month
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - uses: actions/setup-node@v5
        with:
          node-version: "24.x"

      - name: Install
        run: |
          npm install

      - name: Clone
        run: |
          git clone https://github.com/DefinitelyTyped/DefinitelyTyped --depth 1

      - name: Collect
        run: |
          npm start

      - name: Release
        run: |
          npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove DefinitelyTyped
        run: |
          rm -rf DefinitelyTyped
